### ISSUE TITLE
update for Python 3.x

### ISSUE THREAD

**Issue by carvetighter** [jegesh/python-random-access-file-reader#3]
Do you mind if I update your package for Python 3.x?

I'm kicking off the rust as far as development goes and this would be good to help me and you can give me feedback on what to do differently.

This issue I ran into is that StringIO is moved to io.StringIO.

**Comment by jegesh** [comment]
There is already an outstanding PR for this issue.  If you have any comments you can add them there. 
Thanks for your interest.
