### ISSUE TITLE
Python3 please!

### ISSUE THREAD

**Issue by philipperemy** [jegesh/python-random-access-file-reader#7]

**Comment by jegesh** [comment]
I'm sorry, this repo is not really being maintained, but you're more than welcome to submit a PR.

**Comment by jegesh** [comment]
What errors are you getting in python 3?

**Comment by philipperemy** [comment]
I think just the `print "foo bar"`.

**Comment by jegesh** [comment]
There are no `print` commands in the code...
Do you mean the example in the README?

**Comment by philipperemy** [comment]
Yes in the readme!
